/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorge.l
 */
public class creaLista extends javax.swing.JFrame {

           String var;
   Connection con = null;
   Statement stmt = null;
   String titulos[] = {"id","nombre","apPaterno","carrera"};
   String fila[] = new String [10], filas1[]=new String[6], renglones[]=new String[6];
   DefaultTableModel modelo,modelo2,modelo3,modelo4,modelo5;
  int i;
    
    
    public creaLista() {
        initComponents();
        
        modelo2= new DefaultTableModel();
        modelo2.addColumn("id");
        modelo2.addColumn("nombre");
        modelo2.addColumn("apPaterno");
        modelo2.addColumn("carrera");
        
        jTab_tablaLista.setModel(modelo2);
        ////////////////////////////////////////////////////
         modelo4= new DefaultTableModel();
        modelo4.addColumn("id");
        modelo4.addColumn("nombre");
        modelo4.addColumn("cubicilo");
        modelo4.addColumn("horario");
        
        jTable_asesor.setModel(modelo4);
        /////////////////////////////////////////////////////////
        
       
        
        this.setTitle(" crea lista de alumnos");
        this.setLocation(40,50);
        this.setResizable(false);
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/Sat";
            String usuario = "root";
            String contraseña = "itachi";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select* from alumnos");//variable que guarda info de la base de datos
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {  
                   
                   fila[0] = rs.getString("id");
                   fila[1] = rs.getString("nombre");
                   fila[2] = rs.getString("apPaterno");
                   fila[3] = rs.getString("carrera");
                  String exmot= rs.getString("exposicion de motivos");
                  String cartcom= rs.getString("carta compromiso");
                   modelo.addRow(fila); //agrega a las filas    
               }
               jtab_tablaGeneral.setModel(modelo);
               
               
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btn_agregarAsesor = new javax.swing.JButton();
        txt_nomAsesor = new javax.swing.JTextField();
        txt_cubiculo = new javax.swing.JTextField();
        txt_horario = new javax.swing.JTextField();
        txt_correo2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_tablaGeneral = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTab_tablaLista = new javax.swing.JTable();
        btn_buscaAlumno = new javax.swing.JButton();
        txt_nom = new javax.swing.JTextField();
        txt_apepat = new javax.swing.JTextField();
        txt_apmat = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_cel = new javax.swing.JTextField();
        txt_crrera = new javax.swing.JTextField();
        txt_generacion = new javax.swing.JTextField();
        txt_tmtesi = new javax.swing.JTextField();
        txt_dirtesi = new javax.swing.JTextField();
        txt_trabajo = new javax.swing.JTextField();
        btb_agregar_alumno = new javax.swing.JButton();
        btn_eliminar_as = new javax.swing.JButton();
        btn_borraTodo_as = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_terminarLista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_asesor = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_exp_motivos = new javax.swing.JTextField();
        txt_cartaCompromiso = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_agregaAseor = new javax.swing.JButton();
        btn_eliminarAlumno1 = new javax.swing.JButton();
        btn_borraTodo1 = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jMenuItem1.setText("agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregarAsesor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_agregarAsesor.setText("detalles asesor");
        btn_agregarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        txt_nomAsesor.setEditable(false);
        getContentPane().add(txt_nomAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 110, -1));

        txt_cubiculo.setEditable(false);
        getContentPane().add(txt_cubiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, -1));

        txt_horario.setEditable(false);
        getContentPane().add(txt_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 110, -1));

        txt_correo2.setEditable(false);
        getContentPane().add(txt_correo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("base de datos de aumnos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Lista de alumnos para agregar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 220, -1));

        jtab_tablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title4"
            }
        ));
        jtab_tablaGeneral.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jtab_tablaGeneral);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 350, 380));

        jTab_tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTab_tablaLista);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 340, 380));

        btn_buscaAlumno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_buscaAlumno.setText("detalles de alumno");
        btn_buscaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 30));

        txt_nom.setEditable(false);
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 100, -1));

        txt_apepat.setEditable(false);
        getContentPane().add(txt_apepat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 90, -1));

        txt_apmat.setEditable(false);
        getContentPane().add(txt_apmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 90, -1));

        txt_correo.setEditable(false);
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 140, -1));

        txt_cel.setEditable(false);
        getContentPane().add(txt_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 80, -1));

        txt_crrera.setEditable(false);
        getContentPane().add(txt_crrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 70, -1));

        txt_generacion.setEditable(false);
        getContentPane().add(txt_generacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 70, -1));

        txt_tmtesi.setEditable(false);
        getContentPane().add(txt_tmtesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 120, -1));

        txt_dirtesi.setEditable(false);
        getContentPane().add(txt_dirtesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 120, -1));

        txt_trabajo.setEditable(false);
        getContentPane().add(txt_trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 70, -1));

        btb_agregar_alumno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btb_agregar_alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.jpg"))); // NOI18N
        btb_agregar_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_agregar_alumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btb_agregar_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 30, 30));

        btn_eliminar_as.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_eliminar_as.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar.jpg"))); // NOI18N
        btn_eliminar_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_asActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar_as, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 30, 30));

        btn_borraTodo_as.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_borraTodo_as.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ades-icons.png"))); // NOI18N
        btn_borraTodo_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borraTodo_asActionPerformed(evt);
            }
        });
        getContentPane().add(btn_borraTodo_as, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 40, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("carrera");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("generacion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("tema de tesis");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("director de tesis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("trabajo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, -1, -1));

        txt_id.setEditable(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 30, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setText("id");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 30, 20));

        btn_terminarLista.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_terminarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ecommerce-pack (1).png"))); // NOI18N
        btn_terminarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarListaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_terminarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 510, 30, 30));

        jTable_asesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_asesor);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 300, 380));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Nombre");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setText("Cubiculo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("Horario");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 70, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel15.setText("Correo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 50, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel16.setText("exposicion de motivos");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel17.setText("carta compromiso");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 120, -1));
        getContentPane().add(txt_exp_motivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 90, -1));
        getContentPane().add(txt_cartaCompromiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 110, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel18.setText("Terminar lista");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel19.setText("Lista de asesores para agregar");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 240, -1));

        btn_agregaAseor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_agregaAseor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.jpg"))); // NOI18N
        btn_agregaAseor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaAseorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregaAseor, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 30, 30));

        btn_eliminarAlumno1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_eliminarAlumno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar.jpg"))); // NOI18N
        btn_eliminarAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarAlumno1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 30, 30));

        btn_borraTodo1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_borraTodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ades-icons.png"))); // NOI18N
        btn_borraTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borraTodo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_borraTodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 40, 30));

        btn_regresar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 100, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaAlumnoActionPerformed
       
       int resp = JOptionPane.showConfirmDialog(null, "¿acepta terminos y condiciones?");
        if(resp==0){
        
        ResultSet rs = null; 
         var = javax.swing.JOptionPane.showInputDialog(this,"nombre de el alumno","Consulta alumnos",javax.swing.JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT* FROM  alumnos WHERE nombre = '"+var+"'";
        if(var == null)  
        javax.swing.JOptionPane.showMessageDialog(this,"La accion fue cancelada","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
      else {   
        if (var.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Ingresar el nombre del alumno \nque desea consultar","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/Sat";
            String usuario = "root";
            String contraseña = "itachi";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
                rs = stmt.executeQuery(sql);//variable que guarda info de la base de datos
              
            
               while(rs.next()) {  
                   
                String id = rs.getString("id");
                String nom = rs.getString("nombre");
                String pat = rs.getString("apPaterno");
                String mat = rs.getString("apMaterno");
                String ema = rs.getString("email");
                String cel = rs.getString("cel");
                String carr = rs.getString("carrera");
                String gen = rs.getString("generacion");
                String ttes = rs.getString("tem tesi");
                String dtes = rs.getString("dir tesi");
                String tra = rs.getString("trabajo");
                String exmot =rs.getString("exposicion de motivos");
                int motivo = Integer.parseInt (exmot);
                String cartcom=rs.getString("carta compromiso");
                int carta = Integer.parseInt (cartcom);
                 
                   txt_id.setText(id);            
                   txt_nom.setText(nom);
                   txt_apepat.setText(pat);
                   txt_apmat.setText(mat);
                   txt_correo.setText(ema);
                   txt_cel.setText(cel);
                   txt_crrera.setText(carr);
                   txt_generacion.setText(gen);
                   txt_tmtesi.setText(ttes);
                   txt_dirtesi.setText(dtes);
                   txt_trabajo.setText(tra);
                   if(motivo==1){
                   txt_exp_motivos.setText("entregado");
                   }else{
                   txt_exp_motivos.setText("no entregado");
                   }   
                   
                   if(carta==1){
                   txt_cartaCompromiso.setText("entregado");
                   }else{
                   txt_cartaCompromiso.setText("no entregado");
                   } 
               }
               
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }

    }
        
        }
        }else{
        JOptionPane.showMessageDialog(null,"la informacion no se puede mostrar por efectos de privacidad");
        }
    }//GEN-LAST:event_btn_buscaAlumnoActionPerformed

    private void btn_agregarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarAsesorActionPerformed
         ResultSet rs = null; 
         var = javax.swing.JOptionPane.showInputDialog(this,"nombre de el asesor","Consulta asesor",javax.swing.JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT* FROM  asesor WHERE nombre = '"+var+"'";
        if(var == null)  
        javax.swing.JOptionPane.showMessageDialog(this,"La accion fue cancelada","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
      else {   
        if (var.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Favor de ingresar el nombre del asesor ","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/Sat";
            String usuario = "root";
            String contraseña = "itachi";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
                rs = stmt.executeQuery(sql);//variable que guarda info de la base de datos
              
            
               while(rs.next()) {  
                   
                String id = rs.getString("id");
                String nomA = rs.getString("nombre");
                String cub = rs.getString("cubiculo");
                String corA = rs.getString("correo electronico");
                String hora = rs.getString("horario de asesoria");
                
                 
                               
                   txt_nomAsesor.setText(nomA);
                   txt_cubiculo.setText(cub);
                   txt_correo2.setText(corA);
                   txt_horario.setText(hora);
                   
                   
               }
               
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }

    }
                        
       
               
               }
        
    }//GEN-LAST:event_btn_agregarAsesorActionPerformed

    private void btb_agregar_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_agregar_alumnoActionPerformed
        if(txt_nom.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Revise los detalles del alumno \n "
                                               + "para poder agregarlo");
        }else{
         
             String []Filas = new String[6];     
                   Filas[0] = txt_id.getText();
                   
                   Filas[1] = txt_nom.getText();
                   
                   Filas[2] = txt_apepat.getText();
                   
                   Filas[3] = txt_crrera.getText();
                   
                   //Filas[4] = 
                    
                    
                   txt_id.setText(null);            
                   txt_nom.setText(null);
                   txt_apepat.setText(null);
                   txt_apmat.setText(null);
                   txt_correo.setText(null);
                   txt_cel.setText(null);
                   txt_crrera.setText(null);
                   txt_generacion.setText(null);
                   txt_tmtesi.setText(null);
                   txt_dirtesi.setText(null);
                   txt_trabajo.setText(null);
                          
                   modelo2.addRow(Filas); //agrega a las filas    
        }  
    }//GEN-LAST:event_btb_agregar_alumnoActionPerformed

    private void btn_eliminar_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_asActionPerformed
         int filaseleccionada=jTab_tablaLista.getSelectedRow();
            if(filaseleccionada>=0){
                modelo2.removeRow(filaseleccionada);
            }else{
            JOptionPane.showMessageDialog(null,"seleccione un alumno");
            }
    }//GEN-LAST:event_btn_eliminar_asActionPerformed

    private void btn_borraTodo_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borraTodo_asActionPerformed
       int numRenglon=jTab_tablaLista.getRowCount();
        for(int i=numRenglon-1;i>=0;i--){
        modelo2.removeRow(i);
        }
    }//GEN-LAST:event_btn_borraTodo_asActionPerformed

    private void btn_terminarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarListaActionPerformed
        int numRe=jTab_tablaLista.getRowCount();
        int numRen=jTable_asesor.getRowCount();
        if(numRe!=numRen){
             JOptionPane.showMessageDialog(null,"la asignacion de asesor alumno no es la correcta");
        }else{
        if(numRe<1){
            JOptionPane.showMessageDialog(null,"es necesario un minimo 10 alumnos");
        }else{
            if(numRe>25){
            JOptionPane.showMessageDialog(null," esta excediendo el maximo 25 alumnos");
       }else{
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////               
           // int motivo=Integer.parseInt(txt_exp_motivos.getText());
           // int carta=Integer.parseInt(txt_cartaCompromiso.getText());        
           String cad = "no entregado";
           String cad2= txt_exp_motivos.getText();
           String cad3=txt_cartaCompromiso.getText();
       if(cad.equals(cad2)&&cad.equals(cad3)){
              JOptionPane.showMessageDialog(null,"el alumno no cumple con los requisitos");
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
      }else{
               this.dispose();
               lista us= new lista();//instancia de la clase
               us.setVisible(true);
             
                int numRenglon=jTab_tablaLista.getRowCount();
            
               modelo3= new DefaultTableModel();
               modelo3.addColumn("id");
               modelo3.addColumn("nombre");
               modelo3.addColumn("apPaterno");
               modelo3.addColumn("carrera");
             
              
        
               lista.jtab_tabla3.setModel(modelo3);                 
               
               for (int i=0;i<modelo2.getRowCount(); i++) {
               Object fila [] = new Object [modelo2.getColumnCount()];
               for (int j=0; j<modelo2.getColumnCount(); j++){
               fila[j] = modelo2.getValueAt(i,j);
               }
               modelo3.addRow(fila);
            }
               modelo5= new DefaultTableModel(); 
               modelo5.addColumn("id");
               modelo5.addColumn("nombre");
               modelo5.addColumn("cubiculo");
               modelo5.addColumn("horario");
               lista.jTab_tabla4.setModel(modelo5);
               
               for (int i=0;i<modelo4.getRowCount(); i++) {
               Object filas [] = new Object [modelo4.getColumnCount()];
               for (int j=0; j<modelo4.getColumnCount(); j++){
               filas[j] = modelo4.getValueAt(i,j);
               }
               modelo5.addRow(filas);
               
               }
               
           }
                 
                }
          }
        }
    }//GEN-LAST:event_btn_terminarListaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       int filaselec = jtab_tablaGeneral.getSelectedRow();
      
       String []alumno= new String[6];
       alumno[0]= jtab_tablaGeneral.getValueAt(filaselec, 0).toString();
       alumno[1]= jtab_tablaGeneral.getValueAt(filaselec, 1).toString();
       alumno[2]= jtab_tablaGeneral.getValueAt(filaselec, 2).toString();
       alumno[3]= jtab_tablaGeneral.getValueAt(filaselec, 3).toString();
       
        modelo2.addRow(alumno); 
        
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////
   
   ////////////////////////////////////////////////////////////////////////////////////////////////////////////
   //busqueda en tabla alumnos
   try {
            
            String url = "jdbc:mysql://localhost:3306/Sat";
            String usuario = "root";
            String contraseña = "itachi";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               String sql="SELECT* FROM  alumnos WHERE id = '"+alumno[0]+"'";// u
               stmt = con.createStatement();
               ResultSet rsa = stmt.executeQuery(sql);
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rsa.next()) {  
                   
                  
                  String exmot= rsa.getString("exposicion de motivos");
                  String cartcom= rsa.getString("carta compromiso");
                   
                
                  
               
               int motivo = Integer.parseInt (exmot);
              
                 int carta = Integer.parseInt (cartcom);
               
                if(motivo==1){
                   txt_exp_motivos.setText("entregado");
                   }else{
                   txt_exp_motivos.setText("no entregado");
                   }   
                   
                   if(carta==1){
                   txt_cartaCompromiso.setText("entregado");
                   }else{
                   txt_cartaCompromiso.setText("no entregado");
                   } 
               
               
               
             // /* 
             String cad = "no entregado";
           String cad2= txt_exp_motivos.getText();
           String cad3=txt_cartaCompromiso.getText();
             
                if(cad.equals(cad2) || cad.equals(cad3)){
                   JOptionPane.showMessageDialog(null,"el alumno no cuenta con  exposicion de motivos o carta compromiso");  
                  
                   String []asesor= new String[6];
                   asesor[1]="sin asesor";
                   modelo4.addRow(asesor);
                }else{
                   JOptionPane.showMessageDialog(null,"alumno valido");
                   
   //////////////////////////////////////////////////////////////////////////////////////////////////////////////
   ////////////////////////////////////////////////////////////////////////////////////////////////////////////
   //busqueda de asesor para asignar
            ResultSet rs = null;
           var = javax.swing.JOptionPane.showInputDialog(this,"nombre de el asesor","Consulta asesor",javax.swing.JOptionPane.QUESTION_MESSAGE);
            String sqla="SELECT* FROM  asesor WHERE nombre = '"+var+"'";
             if(var == null)  
             javax.swing.JOptionPane.showMessageDialog(this,"La accion fue cancelada","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            else {   
            if (var.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Ingresar el nombre del asesor ","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }else{
        
            try {
            
         
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
                rs = stmt.executeQuery(sqla);//variable que guarda info de la base de datos
              
            
               while(rs.next()) {  
                   
                String id = rs.getString("id");
                String nomA = rs.getString("nombre");
                String cub = rs.getString("cubiculo");
                String corA = rs.getString("correo electronico");
                String hora = rs.getString("horario de asesoria");
                
                 
                   txt_nomAsesor.setText(nomA);
                   txt_cubiculo.setText(cub);
                   txt_correo2.setText(corA);
                   txt_horario.setText(hora);
                   
                   String []asesor= new String[6];            
                   asesor[0]=id;
                   asesor[1]=nomA;
                   asesor[2]=cub;
                   asesor[3]=hora;
                   
                   modelo4.addRow(asesor);
                }
               
               
            }
            catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
             }
            
             }
        
             }
        
        
   ///////////////////////////////////////////////////////////////////////////////////////////////////////////
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////77
                   
                   
                   }   
                   
                  
                   
               //   */ 
               }  
               
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }
    
   
   
   
   
 
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////////7
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////
   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_agregaAseorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaAseorActionPerformed
         ResultSet rs = null; 
         var = javax.swing.JOptionPane.showInputDialog(this,"nombre de el asesor","Consulta asesor",javax.swing.JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT* FROM  asesor WHERE nombre = '"+var+"'";
        if(var == null)  
        javax.swing.JOptionPane.showMessageDialog(this,"La accion fue cancelada","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
      else {   
        if (var.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Favor de ingresar el nombre del asesor ","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/Sat";
            String usuario = "root";
            String contraseña = "itachi";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
                rs = stmt.executeQuery(sql);//variable que guarda info de la base de datos
              
            
              while(rs.next()) {  
                   
                String id = rs.getString("id");
                String nomA = rs.getString("nombre");
                String cub = rs.getString("cubiculo");
                String corA = rs.getString("correo electronico");
                String hora = rs.getString("horario de asesoria");
                
                 
                   txt_nomAsesor.setText(nomA);
                   txt_cubiculo.setText(cub);
                   txt_correo2.setText(corA);
                   txt_horario.setText(hora);
                   
                   String []asesor= new String[6];            
                   asesor[0]=id;
                   asesor[1]=nomA;
                   asesor[2]=cub;
                   asesor[3]=hora;
                   
                   modelo4.addRow(asesor);
                }
               
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }

    }
                        
       
               
               }
        
    }//GEN-LAST:event_btn_agregaAseorActionPerformed

    private void btn_eliminarAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarAlumno1ActionPerformed
         int filaseleccionada=jTable_asesor.getSelectedRow();
            if(filaseleccionada>=0){
                modelo4.removeRow(filaseleccionada);
            }else{
            JOptionPane.showMessageDialog(null,"seleccione un alumno");
            }
    }//GEN-LAST:event_btn_eliminarAlumno1ActionPerformed

    private void btn_borraTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borraTodo1ActionPerformed
        int numRenglon=jTable_asesor.getRowCount();
        for(int i=numRenglon-1;i>=0;i--){
        modelo4.removeRow(i);
        }
    }//GEN-LAST:event_btn_borraTodo1ActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
          this.dispose();//oculta
        logueo p= new logueo();//instancia de la clase usuario
        p.setVisible(true);//lo hace visible
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_agregar_alumno;
    private javax.swing.JButton btn_agregaAseor;
    private javax.swing.JButton btn_agregarAsesor;
    private javax.swing.JButton btn_borraTodo1;
    private javax.swing.JButton btn_borraTodo_as;
    private javax.swing.JButton btn_buscaAlumno;
    private javax.swing.JButton btn_eliminarAlumno1;
    private javax.swing.JButton btn_eliminar_as;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_terminarLista;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTab_tablaLista;
    private javax.swing.JTable jTable_asesor;
    private javax.swing.JTable jtab_tablaGeneral;
    private javax.swing.JTextField txt_apepat;
    private javax.swing.JTextField txt_apmat;
    private javax.swing.JTextField txt_cartaCompromiso;
    private javax.swing.JTextField txt_cel;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_correo2;
    private javax.swing.JTextField txt_crrera;
    private javax.swing.JTextField txt_cubiculo;
    private javax.swing.JTextField txt_dirtesi;
    private javax.swing.JTextField txt_exp_motivos;
    private javax.swing.JTextField txt_generacion;
    private javax.swing.JTextField txt_horario;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_nomAsesor;
    private javax.swing.JTextField txt_tmtesi;
    private javax.swing.JTextField txt_trabajo;
    // End of variables declaration//GEN-END:variables
}
